### ISSUE TITLE
Proposing django-endless-pagination

### ISSUE THREAD

**Issue by tutuca** [jazzband/help#14]
This project https://github.com/frankban/django-endless-pagination, it has been stuck for 3 years now, has some issues with django 1.9 and has spawned already some forks like https://github.com/shtalinberg/django-el-pagination.

**Comment by jezdez** [comment]
Hi @tutuca, unless the main author @frankban agrees we can't just fork a project here

**Comment by kevin-brown** [comment]
Given that django-el-pagination is forked from (and endorsed by) django-endless-pagination, I'd imagine that would be the project (if any) that would be a candidate for migration to Jazzband. But it also appears that @shtalinberg is actively maintaining that project with recent releases.

Note that @frankban updated the README shortly after this ticket was created, making it clear that there are better forks out that. So would it make sense to close off this ticket?

**Comment by Archmonger** [comment]
With 6 years sitting between the original proposal, I'm pinging @shtalinberg to state his thoughts on this.

If a response isn't given we can't single sidedly fork to jazzband.

**Comment by hugovk** [comment]
No reply, let's close this:

* the original project is unmaintained
* there's an active fork
* the original project links to the fork
* No pressing need to move to Jazzband
