### ISSUE TITLE
Proposal: django-user-sessions

### ISSUE THREAD

**Issue by Bouke** [jazzband/help#181]
The project [django-user-sessions](https://github.com/Bouke/django-user-sessions) is looking for a new owner, and I think Jazzband will be a good fit for the project. I'd be interested to hear whether the feeling is mutual, and we can start working on the transfer.

**Comment by ricco386** [comment]
Hello, I would like to volunteer to maintain the repository.

**Comment by mreguly** [comment]
Hi, I would like to also help out and maintain this repository.

**Comment by Bouke** [comment]
Hi @ricco386 and @mreguly, can you register as members? https://jazzband.co/account/github, then please review https://github.com/jazzband/django-user-sessions/pull/108 and we should be able to get this thing started! Thank you.

**Comment by Archmonger** [comment]
Seems like this repo has been migrated to jazzband so I'm closing this ticket.
