### ISSUE TITLE
Proposal: django-simple-history

### ISSUE THREAD

**Issue by treyhunner** [jazzband/help#192]
The current maintainers of [django-simple-history](https://github.com/treyhunner/django-simple-history) would like to move the project to jazzband.

Viability: the project is pretty well established and is currently actively used by me, folks at @cadre (who currently do much of the maintenance), and others.

Documentation: pretty decent documentation exists: https://github.com/treyhunner/django-simple-history

Tests: the test coverage is [pretty great](https://codecov.io/github/treyhunner/django-simple-history?branch=master) and I'd say the tests aren't overly dogmatic

Conduct: our code of conduct is a variation of [Contributor Covenant 1.4](https://github.com/treyhunner/django-simple-history/blob/master/CODE_OF_CONDUCT.md) and we'd be happy to adopt the jazzband CoC instead

Contributing: We have [a contributing file](https://github.com/treyhunner/django-simple-history/blob/master/CONTRIBUTING.rst) already. We could add jazzband references there and put badges in our README.

The project leads should be @rossmechanic and @treyhunner.

If we're approved for transfer, @rossmechanic has agreed to help with updating contributing files, code of conduct, readme, etc. as needed.

**Comment by rossmechanic** [comment]
Hey @jezdez , any update on this? Anything I can do to help push it along? Thanks

**Comment by jezdez** [comment]
Hey friends, I'm going through my huge backlog and see this hasn't moved on, this is good to transfer in my opinion. Once transferred using GitHub's regular repo transfer functionality there will be a ticket to update the rest of the repo to match Jazzband guidelines.

**Comment by treyhunner** [comment]
> Hey friends, I'm going through my huge backlog and see this hasn't moved on, this is good to transfer in my opinion. Once transferred using GitHub's regular repo transfer functionality there will be a ticket to update the rest of the repo to match Jazzband guidelines.

Thanks for the go ahead @jezdez. 😊👍

I just made [the transfer](https://github.com/jazzband/django-simple-history) to the @jazzband org. I believe I selected the correct teams:

![image](https://user-images.githubusercontent.com/285352/83978792-aa249c00-a8be-11ea-8529-0c526794509d.png)

**Comment by jeking3** [comment]
Is this issue now complete?

**Comment by hugovk** [comment]
I'd say so, the project is at Jazzband:

* https://github.com/jazzband/django-simple-history

... the checklist is complete:

* https://github.com/jazzband/django-simple-history/issues/670

... and the project was officially welcomed!

* https://github.com/jazzband/django-simple-history/issues/670#issuecomment-713020203

I'll go ahead and close this, thanks! (We can re-open if I've missed something :)
