### ISSUE TITLE
Please transfer django-user-sessions back to me

### ISSUE THREAD

**Issue by Bouke** [jazzband/help#193]
Hi @jezdez, I’d like you to migrate django-user-sessions back to me. I’ve tried getting jazzband to work for the project, but I’ve been blocked for 3 months now without any resolution so far (see #184). I’ve come to the conclusion that my experiment with jazzband failed and I need to revert and explore other options. Thank you.

**Comment by jezdez** [comment]
Hi Bouke, so I know this isn't great but I just took another look at your issue. It should be fixed now. Do you still want me to move the repo to you?

I am very sorry, for what it's worth, the past months were not ideal in terms of roadie backlog processing and my work to add more roadies and fix some of the procedural issues with Jazzband has slowed down more than I wanted for various reasons, mostly health and lock down related. That is a fact that I can't do much about other than stating and hoping for your understanding.

**Comment by rossmechanic** [comment]
@jezdez anything I can do to help on the roadie side of things? Happy to contribute and help take some work off of the roadie backlog.

**Comment by jezdez** [comment]
@Bouke Hey, so just checking in, I'm ready to transfer it back to you if you still want to do that.

**Comment by tim-schilling** [comment]
@Bouke, should this be closed as per jazzband/django-user-sessions#123?

**Comment by Bouke** [comment]
Yes that is fine.
