### ISSUE TITLE
Proposal: django-cookie-consent

### ISSUE THREAD

**Issue by 9mido** [jazzband/help#214]
## Project Details
django-cookie-consent

## Project Description
django-cookie-consent is a reusable application for managing various cookies and visitors consent for their use in Django project. It is a complete replacement for something like a paid cookie management solution such as OneTrust CookiePro. But it is free to use for django developers. 

Features:

- cookies and cookie groups are stored in models for easy management through Django admin interface
- support for both opt-in and opt-out cookie consent schemes
- removing declined cookies (or non accepted when opt-in scheme is used)
- optionally logging user actions when they accept and decline various cookies
- easy adding new cookies and seamlessly re-asking for consent for new cookies

## Project Leads
@bmihelac

## Confirmation of Guidelines

Please confirm the following:

- I am not the project owner, but @bmihelac who is the owner has expressed interest in jazzband. See https://github.com/bmihelac/django-cookie-consent/issues/38. I just wanted to help move things along. I do not want to maintain django-cookie-consent myself as I am not experienced enough. 

- This project is a [viable candidate](https://jazzband.co/about/guidelines#viability) for Jazzband. See the above django-cookie-consent issue showing details as to why this library is a viable candidate for jazzband and the django community. 

- This project fulfills the [documentation requirements](https://jazzband.co/about/guidelines#documentation).

- This project is [tested](https://jazzband.co/about/guidelines#tests).

- I cannot speak for @bmihelac but it seems that he would be happy to adopt Jazzband's [code of conduct](https://jazzband.co/about/guidelines#conduct) in this project.

-  I cannot speak for @bmihelac but it seems that he is happy to include Jazzband's [contributing guidelines](https://jazzband.co/about/guidelines#contributing-guidelines) in this project.

**Comment by bmihelac** [comment]
Hello everyone, 

@9mido thank you for the time and effort to write this. 

If this project is of interest in jazzband community I would be more than happy to undertake all necessary actions for easy transition.

**Comment by MrCordeiro** [comment]
`django-cookie-consent` seems well-suited for Jazzband. @bmihelac, if you want to, would you please take a moment and transfer the repo to the Jazzband organization via [GitHub's transfer feature](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization)? That way we can collectively work toward getting new versions of the project released to PyPI.

**Comment by bmihelac** [comment]
Hello everyone! I have initiated transfer to jazzband. TODO list for implementing Jazzband guidelines is here:
https://github.com/jazzband/django-cookie-consent/issues/64
