### ISSUE TITLE
Proposal: prance

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [jazzband/help#215]
## Project Details
prance : https://github.com/RonnyPfannschmidt/prance

## Project Description
prance manages openapi bundling/validation for python
i took up the maintainer role today

## Project Leads
- @RonnyPfannschmidt

## Confirmation of Guidelines

Please confirm the following:

- [x] I am the project owner, or have permission from the project owner, to request a transfer.

- [x] This project is a [viable candidate](https://jazzband.co/about/guidelines#viability) for Jazzband.

- [x] This project fulfills the [documentation requirements](https://jazzband.co/about/guidelines#documentation).

- [x] This project is [tested](https://jazzband.co/about/guidelines#tests).

- [x] I am happy to adopt Jazzband's [code of conduct](https://jazzband.co/about/guidelines#conduct) in this project.

- [x] I am happy to include Jazzband's [contributing guidelines](https://jazzband.co/about/guidelines#contributing-guidelines) in this project.

i'm currently verifying the doc requirements and i'm also in conversation with the https://github.com/OpenAPITools/ org about placing it there

**Comment by jezdez** [comment]
This isn't covered by the guidelines yet, but I'm usually checking what license is used and prance is using the very rare MITNFA license, which isn't OSI approved. I suggest to switch to a regular OSI approved license instead before the transfer.

**Comment by jezdez** [comment]
Some background how the license came to be for npm: https://github.com/Level/packager/issues/1

**Comment by RonnyPfannschmidt** [comment]
working on that now, thanks for the references

**Comment by RonnyPfannschmidt** [comment]
closing this for now as prance is not ready for a  move here
