### ISSUE TITLE
PyPI Release: <PACKAGE NAME>

### ISSUE THREAD

**Issue by NeverLiez** [jazzband/help#217]
# PyPI Release
Please read the information about [releases](https://jazzband.co/about/releases) on the website before submitting an issue. In particular, if a project already has project leads assigned, then you'd be better off creating an issue in the individual project, and asking the leads to do a release.

In the event there are no project leads, you're in the right place! Please link the project for which you'd like to create a release.

**Comment by jezdez** [comment]
@NeverLiez I'm not sure if you intented to open an empty issue. Closing.
