### ISSUE TITLE
PyPI Release: django-redis

### ISSUE THREAD

**Issue by terencehonles** [jazzband/help#218]
# PyPI Release

I'm filing this issue to make sure it's not lost, but we're working to finish https://github.com/jazzband/django-redis/issues/430.

Based on the discussion https://github.com/jazzband/django-redis/issues/430#issuecomment-812323073 @WisdomPill and I can be marked as project leads, and I also opened a PR https://github.com/jazzband/django-redis/pull/512 which I think will upload to the private registry (copied from another Jazzband project). I'm not sure what else needs to be done in order to allow us to automatically upload releases, but we'd like to finish the process :slightly_smiling_face:

**Comment by jeking3** [comment]
It looks like this was done, as the latest release of django-redis is 5.2.0 as of Dec 2021?
