### ISSUE TITLE
Django-Redis on Heroku: Error while reading from socket: (104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by rajesitb** [jazzband/help#223]
I've uploaded my project on Heroku. Settings in the settings.py are as per the docs.

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get('REDIS_URL'),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

 However when I load a view function with "@cache_page" decorator, I get the error : **Error while reading from socket: (104, 'Connection reset by peer')**. The Images of error report is attached. Pictures are numbered in sequence.

Same error is also displayed when I run the following in the shell

>>> from django.core.cache import cache
>>> cache.set("foo", "value", timeout=25)

This too throws a connection error.

Please suggest how to overcome this error!

![Picture5](https://user-images.githubusercontent.com/56825534/120586726-aa179780-c451-11eb-9b7c-7785560b2a29.png)
![Picture6](https://user-images.githubusercontent.com/56825534/120586740-af74e200-c451-11eb-9309-aaab52a9094d.png)
![Picture](https://user-images.githubusercontent.com/56825534/120586749-b26fd280-c451-11eb-91a2-4edc1f359d8b.png)
![Picture1](https://user-images.githubusercontent.com/56825534/120586752-b4399600-c451-11eb-934e-d6f43dffaed9.png)
![Picture2](https://user-images.githubusercontent.com/56825534/120586754-b6035980-c451-11eb-9ce9-943e869ec1c9.png)
![Picture3](https://user-images.githubusercontent.com/56825534/120586761-b8fe4a00-c451-11eb-97a2-75abbbd5ad45.png)
![Picture4](https://user-images.githubusercontent.com/56825534/120586771-bc91d100-c451-11eb-83fa-9f2e4900e011.png)

**Comment by jezdez** [comment]
Hi there, I'm sorry but this issue tracker is about getting help with the Jazzband organization's funcationlity not individual project usage. You may get better help in the project's issue tracker: https://github.com/jazzband/django-redis/issues or on StackOverflow.
