### ISSUE TITLE
Project Lead: imaplib2

### ISSUE THREAD

**Issue by piyueh** [jazzband/help#227]
# Project lead request

### Please explain why you'd fit the role of project lead for this project.

No one is actively participating in the development/maintenance of `imaplib2`, so I'll take the role until someone is willing to take the responsibility. I can at least oversee the release of `imaplib2` on PyPI and review minor PRs.

Also, I'm the packager, maintainer, and a user of an Arch Linux AUR package, `offlineimap3`, which depends on `imaplib2`. So as long as I'm still using `offlineimap3`, I'll make sure `imaplib2` at least still works with `offlineimap3`.

### Explain any prior involvement in the project.

I initiated the work that gives `imaplib2` an MIT license so that it is officially okay (at least in the US) for anyone to use, contribute to, and derive from the code. I also did some works to make `imaplib2` meet the Jazzband guidelines.

### If there are existing project leads, they should also agree to this change.

There are no existing project leads. @graingert was the previous project maintainer before transferring it to Jazzband. He may still be willing to take the project lead role. If not, otherwise, it would be nice to have his agreement on me taking the role.

**Comment by graingert** [comment]
Lgtm

**Comment by jezdez** [comment]
Done! Thanks @piyueh for volunteering.
