### ISSUE TITLE
CI on pip-tools is broken due to invalid actions permissions

### ISSUE THREAD

**Issue by atugushev** [jazzband/help#230]
The CI workflow is [failing](https://github.com/jazzband/pip-tools/actions/runs/931446852) with the following error:
![image](https://user-images.githubusercontent.com/7377671/121782640-c85d6000-cbd4-11eb-91f7-6f516216f2a7.png)

### How to fix

Update the current list of allowed actions to:

- `deatsnakes/action@*`
- `pypa/gh-action-pypi-publis@*`

**Comment by jezdez** [comment]
Try again, please.

**Comment by atugushev** [comment]
It works now. Thanks for the fix! 👍🏻
