### ISSUE TITLE
Project Lead: django-eav2

### ISSUE THREAD

**Issue by Dresdn** [jazzband/help#231]
# Project lead request

As part of the Jazzband on-boarding, the project needs a project lead. Currently, lvm and myself have been two of the primary contributors, and lvm has stated they do not have much time to work on django-eav2.

As I'm leading the way towards the implementing the Jazzband guidelines, I'd like to volunteer to be the project lead.

**Comment by jezdez** [comment]
@lvm Can you please confirm this here or in https://github.com/jazzband/django-eav2/issues/69?

**Comment by Dresdn** [comment]
@jezdez I forgot to add a link to the comment that prompted this request, in case @lvm doesn't respond here.

https://github.com/jazzband/django-eav2/pull/70#issuecomment-874091050

**Comment by lvm** [comment]
@jezdez I confirm this.
In fact, i suggested this to @Dresdn so I don't block any of his work. 

https://github.com/jazzband/django-eav2/pull/70#issuecomment-874091050

**Comment by Dresdn** [comment]
@jezdez do you need anything else to proceed with this request?

**Comment by Dresdn** [comment]
@jezdez @jstockwin @hugovk Can you assist with this? I'd like to go ahead and check off some of the items on implementing the guidelines, but am unable to do so without access to the project settings.

**Comment by jstockwin** [comment]
@Dresdn There's nothing I can do to help here, sorry. I don't have access to these settings.

**Comment by jezdez** [comment]
Sorry for the long wait, I added both @lvm and @Dresdn as project leads: https://jazzband.co/projects/django-eav2
