### ISSUE TITLE
pre-commit.ci for django-payments

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband/help#235]
I'd like to use pre-commit.ci for django-payments. 

It's a very very fast and zero-maintainence CI that runs pre-commit hooks on each push. It also pushes any auto-fixes that may come out, and sends weekly PRs updating hooks.

I see that it's currently active for other jazzband projects, but needs to be enabled manually for each one. Can you enable it for django-payments?

See also https://github.com/jazzband/django-payments/issues/259

**Comment by jezdez** [comment]
Sorry for the delay, I just approved your request.

**Comment by WhyNotHugo** [comment]
Thanks!
