### ISSUE TITLE
Integrating django-oauth-toolkit and Okta

### ISSUE THREAD

**Issue by mehdi123** [jazzband/help#238]
Hi there,

I am working on a django application (using DRF) which already has been integrated with oauth toolkit. Now there is a requirement to use Okta as the user management. Do you have any information/guidance how can I integrate the django oauth toolkit with Okta?

Thank you.

**Comment by tim-schilling** [comment]
@mehdi123 can you recreate this question in https://github.com/jazzband/django-oauth-toolkit? This project is for for Jazzband internals and questions regarding the organization, its policies, processes, etc.
