### ISSUE TITLE
Project Lead:  icalevents 

### ISSUE THREAD

**Issue by eigenmannmartin** [jazzband/help#252]
# Project lead request

Thank you for accepting icalevents into jazzband after I proposed it.
I am using icalevents @nalpch in a production environment and I revived/fixed multiple issues in the project.
I can not promise that I can respond to every request in the project within seconds but I can promise that I will drive the development and increase the accuracy and quality.
It would be an honor to be project lead for this particular library and therefore be "more" part of jazzband :smile: 

cheers
Martin

**Comment by eigenmannmartin** [comment]
@jezdez Is there anything I can help you with? The project https://github.com/jazzband/icalevents is essentially stalled right now.
Can you please allow me to publish new versions. Thank you so much! :-D

**Comment by eigenmannmartin** [comment]
@jezdez Is there any update?

**Comment by eigenmannmartin** [comment]
@jezdez After more than 6 months of waiting I am a bit helpless right now.

**Comment by jezdez** [comment]
Done!
