### ISSUE TITLE
PyPI Release: django-robots

### ISSUE THREAD

**Issue by mpoli** [jazzband/help#259]
# PyPI Release

django-robots had a README update to reflect support to Django 3.2 and 4, and that support sits in HEAD by commit https://github.com/jazzband/django-robots/commit/70da7606974b915d57e038f8bdf31c0b21be7e45 but hasn't been release. django-robots fell into the 3.1->3.2 AutoField breaking change in Django, and needs this update to become compatible with 3.2 and 4.

So currently the docs reflect what's sitting in HEAD, but not what is in the current release (version 4.0.0), which leads to great confusion by newcomers and new users, especially because the version number (4.0.0) is identical to the Django 4 version, but incompatible.

A request for a release has been [sitting in the Issues](https://github.com/jazzband/django-robots/issues/117) for nearly a month now, unattended.

So, please pack a release of django-robots that will add support to Django 3.2 and 4 and sync with the current documentation.

**Comment by tony** [comment]
[5.0b1](https://pypi.org/project/django-robots/5.0b1/) is released on PyPI.  Sorry for the delay.  I will release final after we have a few confirmations 

For now I will close this as final release is imminent

**Comment by mpoli** [comment]
Thanks, @tony!
