### ISSUE TITLE
A couple of issues with release 1.6.0 of django-oauth-toolkit

### ISSUE THREAD

**Issue by n2ygk** [jazzband/help#261]
Hey @jezdez @MattBlack85:

I've run into a couple of issues with this release:

- RTFD.io builds have been failing for a while. See the latest at: https://readthedocs.org/projects/django-oauth-toolkit/builds/15577701/
- https://pypi.org/project/django-oauth-toolkit/ shows the release as 1.6.0 but the pypi package badge says 1.5.0.

Can you help?

**Comment by hugovk** [comment]
> * [pypi.org/project/django-oauth-toolkit](https://pypi.org/project/django-oauth-toolkit/) shows the release as 1.6.0 but the pypi package badge says 1.5.0.

It now shows 1.6.0, must have been cached.

![image](https://user-images.githubusercontent.com/1324225/146722089-36f721cd-1fbc-4b63-95d6-11e374174e2a.png)

**Comment by n2ygk** [comment]
I'll try and look at rtfd today. I suspect it might have to do with django 4 being released and the import not specifying < 4. There are issues with django 4.

**Comment by n2ygk** [comment]
@jezdez Thanks for fixing the RTFD stuff!
