### ISSUE TITLE
Proposal: django-dbbackup

### ISSUE THREAD

**Issue by Archmonger** [jazzband/help#262]
# Project Proposal

Please fill in the details below to confirm you adhere to the [Jazzband Guidelines](https://jazzband.co/about/guidelines), and also add the package name to the issue title.

## Project Details
[django-dbbackup](https://github.com/django-dbbackup/django-dbbackup)

## Project Description
This Django application provides management commands to help backup and restore your project database and media files with various storages such as Amazon S3, Dropbox, local file storage or any Django storage.

## Project Leads
@Archmonger 
@johnthagen

## Confirmation of Guidelines

Please confirm the following:

- [x] I am the project owner, or have permission from the project owner, to request a transfer.

- [x] This project is a [viable candidate](https://jazzband.co/about/guidelines#viability) for Jazzband.

- [x] This project fulfills the [documentation requirements](https://jazzband.co/about/guidelines#documentation).

- [x] This project is [tested](https://jazzband.co/about/guidelines#tests).

- [x] I am happy to adopt Jazzband's [code of conduct](https://jazzband.co/about/guidelines#conduct) in this project.

- [x] I am happy to include Jazzband's [contributing guidelines](https://jazzband.co/about/guidelines#contributing-guidelines) in this project.

**Comment by johnthagen** [comment]
I also support this.

**Comment by jezdez** [comment]
Looks good to me! Feel free to initiate the repo transfer to the Jazzband org.

**Comment by Archmonger** [comment]
Transfer has been submitted 🥂

**Comment by jezdez** [comment]
Transfer TODOs: https://github.com/jazzband/django-dbbackup/issues/417
