### ISSUE TITLE
Help making py 3.10 "required" to pass in django-oauth-toolkit

### ISSUE THREAD

**Issue by n2ygk** [jazzband/help#263]
Does a branch protection rule need to be updated by @jazzband/roadies to make py3.10 tests `Required` or am I missing somewhere else where this is set?

![image](https://user-images.githubusercontent.com/4356471/148648383-69edff7c-b777-4c8a-8b47-5deea707cb41.png)

**Comment by hugovk** [comment]
Yes, it needs a roadie to go to https://github.com/jazzband/django-oauth-toolkit/settings/branches and add the new check.

**Comment by jezdez** [comment]
This is done.
