### ISSUE TITLE
Project Lead: django-widget-tweaks

### ISSUE THREAD

**Issue by aleksihakli** [jazzband/help#264]
# Project lead request

Hey @camilonova and @jezdez. I was making package updates for a few projects and noticed that @camilonova is the only project lead for [django-widget-tweaks](https://jazzband.co/projects/django-widget-tweaks). I was wondering if it would be OK if I joined the team for a coleadership for updating the specific package since I've been coordinating minor updates and releases for it for a while? I hate bothering people over email for minor releases with version bumps etc.

**Comment by jezdez** [comment]
Done.

**Comment by aleksihakli** [comment]
Thank you :)
