### ISSUE TITLE
Proposal: dj-database-url

### ISSUE THREAD

**Issue by jacobian** [jazzband/help#267]
# Project Proposal

Hello friends! [dj-database-url](https://github.com/jacobian/dj-database-url/) needs a new home.

## Project Details
dj-database-url converts database URLs into a dict for Django's `DATABASES` setting, e.g. to read `env[DATABASE_URL]` on many PaaS platforms.

## Project Description
I picked up ownership of the original package when the maintainer wanted to step back. But I've not been a great steward, asked for help (see jacobian/dj-database-url#152), and we decided the ideal outcome would be getting it under the @jazzband banner, with a set of new maintainers, where it can continue to get the love it deserves.

## Project Leads
@mattseymour 
@scuerda 
@adamchainz
@ParthS007
@dcwatson 
(I'm here strictly to facilitate transfer, but wouldn't be a maintainer after the transfer)

## Confirmation of Guidelines

Please confirm the following:

- [x] I am the project owner, or have permission from the project owner, to request a transfer.

- [x] This project is a [viable candidate](https://jazzband.co/about/guidelines#viability) for Jazzband.

- [x] This project fulfills the [documentation requirements](https://jazzband.co/about/guidelines#documentation).

- [x] This project is [tested](https://jazzband.co/about/guidelines#tests).

- [x] I am happy to adopt Jazzband's [code of conduct](https://jazzband.co/about/guidelines#conduct) in this project.

- [x] I am happy to include Jazzband's [contributing guidelines](https://jazzband.co/about/guidelines#contributing-guidelines) in this project.

---

💚  y'all , and thanks @mattseymour @scuerda @adamchainz @ParthS007 @dcwatson for the idea and for volunteering to take this over from me.

**Comment by mattseymour** [comment]
Is there anything i can do for the time being to help move this forward @jezdez?

**Comment by jezdez** [comment]
@mattseymour Oh I missed the original discussion in https://github.com/jacobian/dj-database-url/issues/152 and assumed there would need to be more discussion here first by the people mentioned in this ticket. I just got another notification from there where you said there wasn't any progress on the Jazzband side.

So yeah, @jacobian this looks good, feel free to transfer the repo to the Jazzband org using the regular GitHub functionality, the jazzband bot will open an issue automatically with additional TODO items to finalize the transition. We can close this ticket here once the transfer has happened. Hope that helps!

**Comment by mattseymour** [comment]
@jezdez thanks for the update. I am sure we will be able to get things going soon.

**Comment by jacobian** [comment]
Fantastic, thanks @jezdez! Happy to move this along.

Unfortunately I am being told

> You don’t have the permission to create public repositories on jazzband

When trying to initiate the transfer (via settings -> general -> transfer). Am I doing it wrong or is there something I'm missing?

**Comment by jezdez** [comment]
> > Fantastic, thanks @jezdez! Happy to move this along.
> > Unfortunately I am being told
> > > You don’t have the permission to create public repositories on jazzband
> > 
> > 
> > When trying to initiate the transfer (via settings -> general -> transfer). Am I doing it wrong or is there something I'm missing?
> 
> Oh, right, I should have mentioned that you'll need to join Jazzband first, to be able to transfer it to the org. That's a limitation of GitHub that you can't transfer a repo to an org that you aren't a member of. Go to https://jazzband.co/join and follow the instructions and let me know if you have any issues.

To clarify, you can leave the org after the repo transfer again on https://jazzband.co/account.

**Comment by jacobian** [comment]
BOOM: https://github.com/jazzband/dj-database-url

Thanks  @jezdez!

@mattseymour @scuerda @adamchainz @ParthS007 @dcwatson - up to y'all now, I think my work is done. Thanks so much!
