### ISSUE TITLE
Project Lead: django-fsm-log

### ISSUE THREAD

**Issue by MRigal** [jazzband/help#268]
# Project lead request

My involvement in the project is mostly limited to bug triage and code reviews. I also started the process of migrating the project from the gizmag abandoned organization to jazzband.

Furthermore, to limit the situations where people are stuck after for example a major Django release, I do think it is a good idea to have more than one lead. 

@ticosax is the current project lead and has agreed/proposed to have me as co-lead. https://github.com/jazzband/django-fsm-log/pull/114#issuecomment-1013422683

Cheers

**Comment by jezdez** [comment]
Just added you as project lead! Thank you for volunteering @MRigal 🥳 

Please make sure to read the docs about [releases](https://jazzband.co/about/releases), [guidelines](https://jazzband.co/about/guidelines), [security](https://jazzband.co/about/security) and [FAQ](https://jazzband.co/about/faq). And a gentle reminder that you agree to follow the Jazzband [Code of Conduct](https://jazzband.co/about/conduct).

BTW, while looking at the permissions, I noticed that @ticosax had so far admin permissions for the repo, and you as well, which seems to have been an oversight of the transfer (correct me if I'm wrong). For policy reasons you both need to have the same permission level as any other project lead.
