### ISSUE TITLE
jazzband.co login 500 error

### ISSUE THREAD

**Issue by n2ygk** [jazzband/help#270]
Tried to login and got a 500 error at: Sun, 23 Jan 2022 22:37:59 GMT

```
Request URL: https://jazzband.co/account/github/authorized?code=05b5af5931219b805cf7&state=ohCZGau8nKP398pkg40jvhGyaRlIJB
Request Method: GET
Status Code: 500 
Remote Address: 116.202.0.125:443
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by jezdez** [comment]
Yeah, seeing that as well, seems to be a connectivity issue between the server and the GitHub API. Will investigate..

**Comment by jezdez** [comment]
Seems to work for me again, @n2ygk can you check on your end?

**Comment by n2ygk** [comment]
> Seems to work for me again, @n2ygk can you check on your end?

Yes, good now. Thanks.
