### ISSUE TITLE
PyPI Release: sorl-thumbnail 12.8.0

### ISSUE THREAD

**Issue by claudep** [jazzband/help#272]
As we don't get feedback by @camilonova recently, who is the project lead, is it possible to make a sorl-thumbnail release, please?

**Comment by jezdez** [comment]
Sure, the changes look good, feel free to create a release and lemme know when you've done that.

**Comment by claudep** [comment]
12.8.0 tag pushed and release created on GitHub.

**Comment by jezdez** [comment]
Done!

**Comment by claudep** [comment]
Thanks a lot!
