### ISSUE TITLE
PyPI Release: django-revproxy

### ISSUE THREAD

**Issue by alenavolk** [jazzband/help#273]
Please prepare release of django-revproxy 0.11.0. Changelog has been updated.

**Comment by jeking3** [comment]
@alenavolk if you grab and modify the [release.yml workflow file from the django-simple-history](https://github.com/jazzband/django-simple-history/blob/master/.github/workflows/release.yml) (change the if statement around line 10 for your repository as well as the last line, both of which refer to django-simple-history) and then make a release in GitHub it will upload a package to jazzband and make it easier for the roadies to get it to pypi.

Also see: https://jazzband.co/about/releases

**Comment by andruten** [comment]
This has been addressed in https://github.com/jazzband/help/issues/330.
