### ISSUE TITLE
transfer of django-permission

### ISSUE THREAD

**Issue by JanMalte** [jazzband/help#274]
What is the state of the transfer of the `django-permission` project?
Is there anything we can do? The repository still seems to be archived.

I would like to provide changes to get the project working with django 3.2 and 4.0.
Hopefully there can soon be a new release with the changes to update projects using `django-permission`.

**Comment by JanMalte** [comment]
@jezdez Is there anything I can do to get the project active again?

There are a some changes neccessary to get this project running with Python 3.10 or Django 3.2 / 4.0

Currently this project is blocking updates for many projects.

**Comment by JanMalte** [comment]
@hugovk @jezdez This is still an issue.

**Comment by hugovk** [comment]
https://github.com/jazzband/django-permission

Unfortunately @jezdez is the [only roadie](https://jazzband.co/roadies) and only roadies can give those permissions.

See also https://github.com/jazzband/help/issues/196.

It looks like the transfer was only suggested, I only see https://github.com/jazzband/django-permission/issues/85 and no usual transfer checklist, so I've no idea what's going on there.

**Comment by JanMalte** [comment]
I've forked `django-permission` to maintain the library for now.
https://github.com/JanMalte/django-permission2

There is no need to work on the transfer right now from my side.
Feel free to close the issue. Maybe just add a note to the repo about the forked one.

**Comment by hugovk** [comment]
> I've forked `django-permission` to maintain the library for now. [JanMalte/django-permission2](https://github.com/JanMalte/django-permission2)

Thank you for forking the archived https://github.com/jazzband/django-permission and releasing at https://pypi.org/project/django-permission2/

> There is no need to work on the transfer right now from my side. Feel free to close the issue. Maybe just add a note to the repo about the forked one.

Okay, closing!

The project is archived, so it'd need a [roadie](https://github.com/jazzband/help/issues/196) to unarchive it first, add the note, then re-archive.

Another suggestion: you could ask the maintainers of https://pypi.org/project/django-permission/ to let you re-use the name. Or if the project has been abandoned, have a look at [PEP 541](https://peps.python.org/pep-0541/) and request transfer of the `django-permission` name on PyPI.
