### ISSUE TITLE
django-payments: docs not building

### ISSUE THREAD

**Issue by WhyNotHugo** [jazzband/help#276]
The docs for `django-payments` don't seem to be building: https://django-payments.readthedocs.io/en/latest/index.html

Not sure how old the published version is, but it's definitely not one of the latest releases. Can I maybe have access to the project in readthedocs so I can see the build logs myself?

Setting up per-PR builds would also be useful to review changes live before merging, can that be done too?

Thanks!

**Comment by hugovk** [comment]
RTD build logs are public:

https://readthedocs.org/projects/django-payments/builds/

And failing with:

> Problem in your project's configuration. Invalid "python.version": expected one of (2, 2.7, 3, 3.5, 3.6, 3.7, 3.8, pypy3.5), got 3.9

https://readthedocs.org/projects/django-payments/builds/16387309/

**Comment by WhyNotHugo** [comment]
Fixed via https://github.com/jazzband/django-payments/pull/302

I've created a separate ticket to track enabling RTD for PRs: https://github.com/jazzband/django-payments/issues/355
