### ISSUE TITLE
Help solution for Issues - Django-DBBackup

### ISSUE THREAD

**Issue by gilsonluiz** [jazzband/help#277]
Helo,

This inssue [here](https://github.com/jazzband/django-dbbackup/issues/397).

How to solve?

Thank's

**Comment by Archmonger** [comment]
@gilsonluiz This is not the correct location to request help with django-dbbackup.

There are several existing bugs with this repo. Please see this issue for my plans on resolving them:
- https://github.com/jazzband/django-dbbackup/issues/423
