### ISSUE TITLE
Project Lead: dj-database-urls

### ISSUE THREAD

**Issue by mattseymour** [jazzband/help#278]
# Project lead request

I have been using the dj-database-urls project for a while now and noticed it has not been getting the love it needs. So with help from @jacobian and others I have been pushing to get the project migrated to a more permenant home.
I have submitted a number of patches and PRs recently to help move the project towards the goal of being updated and maintained on a more regular basis.

I hope that I will be able to get the project to the jazzband standard and clear the backlog of many PRs and issues.

**Comment by jacobian** [comment]
Huge 👍🏻  from me (I'm the previous maintainer), in case its needed.

Also at some point folks'll need me to add them over on PyPI. When you're ready can y'all open an issue somewhere and tag me on it?

**Comment by jezdez** [comment]
Done!

Please make sure to take a look at the Jazzband [code of conduct](https://jazzband.co/about/conduct), [general guidelines](https://jazzband.co/about/guidelines), [release process](https://jazzband.co/about/releases) and [security policy](https://jazzband.co/about/security). Thank you!
