### ISSUE TITLE
Project Lead: django-invitations

### ISSUE THREAD

**Issue by valberg** [jazzband/help#279]
# Project lead request

I've put some work in getting the project ready for a new release. I don't have any specific qualifications other than I use django-invitations in different projects and want to give back.

I know that @brylie also expressed interest in being a project lead in https://github.com/jazzband/help/issues/237 - I don't mind sharing the project lead role .

**Comment by brylie** [comment]
I'm fine with @valberg being project lead :-)

**Comment by jezdez** [comment]
Added @valberg to the project. 🥳 

Please make sure to read the docs about [releases](https://jazzband.co/about/releases), [guidelines](https://jazzband.co/about/guidelines), [security](https://jazzband.co/about/security) and [FAQ](https://jazzband.co/about/faq). And a gentle reminder that you agree to follow the Jazzband [Code of Conduct](https://jazzband.co/about/conduct).

**Comment by jezdez** [comment]
> I'm fine with @valberg being project lead :-)

I understood that comment as you NOT being interested in being co-project lead. Please let me know if that's not what you intended and also want to be project lead.

**Comment by valberg** [comment]
> Added @valberg to the project. 🥳 
> 
> Please make sure to read the docs about [releases](https://jazzband.co/about/releases), [guidelines](https://jazzband.co/about/guidelines), [security](https://jazzband.co/about/security) and [FAQ](https://jazzband.co/about/faq). And a gentle reminder that you agree to follow the Jazzband [Code of Conduct](https://jazzband.co/about/conduct).
> 

Great! Thanks @jezdez! I'll read up on everything and of course I agree to follow the Code of Conduct 😊

**Comment by brylie** [comment]
I can be the co-project lead, so there is a fall-back to ensure PRs get reviewed, etc.

**Comment by jezdez** [comment]
> @jezdez, I can be the co-project lead, so there is a fall-back to ensure PRs get reviewed, etc.

Excellent, thank you! Done: https://jazzband.co/projects/django-invitations
