### ISSUE TITLE
PyPI Release: wagtailmenus

### ISSUE THREAD

**Issue by MrCordeiro** [jazzband/help#280]
# PyPI Release

Hello, we have updated wagtailmenus to be compatible with Django 4.0 and it would be great if it could be released for PyPi.

**Comment by jeking3** [comment]
@MrCordeiro it looks like you added a release.yml workflow but it hasn't run yet because no release has been created containing that change.  Perhaps the 3.1 release can pick that up and upload package(s) to jazzband so the roadies can push to pypi.

**Comment by MrCordeiro** [comment]
Hi, @jeking3,

The workflow fails with the following error

```
Uploading distributions to https://jazzband.co/projects/wagtailmenus/upload
Uploading wagtailmenus-3.1-py3-none-any.whl
Received "500: INTERNAL SERVER ERROR" Package upload appears to have failed.
```


It the same error I got last time I tried by myself. There are not other details :(

**Comment by jeking3** [comment]
Is it possible that `wagtailmenus-3.1-py3-none-any.whl` was already uploaded?  The server seems to reject duplicates - I saw the same error when I tried to re-spin a pre-release build and upload it with the same name.  The roadies recommended bumping the patch version (so in this case, 3.1.1) and doing another release if there were changes or fixes.  I don't think there's much support for preflight / pre-release right now.

**Comment by sowinski** [comment]
> Hi, @jeking3,
> 
> The workflow fails with the following error
> 
> ```
> Uploading distributions to https://jazzband.co/projects/wagtailmenus/upload
> Uploading wagtailmenus-3.1-py3-none-any.whl
> Received "500: INTERNAL SERVER ERROR" Package upload appears to have failed.
> ```
> 
> It the same error I got last time I tried by myself. There are not other details :(

Is this a jazzband related server bug?

**Comment by craigds** [comment]
this issue is holding up adoption of wagtailmenus 3.1 which in turn is preventing projects from upgrading to django 4.x

**Comment by sowinski** [comment]
What can we do?

**Comment by jezdez** [comment]
I've added the needed release key to the repo's secrets. The workflow should now be running through. But: until there is a dedicated project lead to verify and confirm releases, that will fall back to me, which can take a while.

**Comment by MrCordeiro** [comment]
Understood and thanks @jezdez!
This was a more urgent release since it was preventing people from upgrading their Django/Wagtail.

I'll study the inner working of this project on the weekend to see if I think I can manage as its lead.

**Comment by MrCordeiro** [comment]
Btw, the workflow runs, but we still need to wait for you to confirm the release, should we re-open this ticket, @jezdez?

I mean, the ticket was for releasing the package, not only making the workflow run (though that was part of it).

**Comment by jezdez** [comment]
@MrCordeiro This issue is fine, the next steps should be discussed in https://github.com/jazzband/wagtailmenus/issues/419 (release) and https://github.com/jazzband/wagtailmenus/issues/409 (project leads).
