### ISSUE TITLE
PyPI Release:  django-simple-history-3.1.0

### ISSUE THREAD

**Issue by jeking3** [jazzband/help#283]
# PyPI Release Assistance

Please note: if you read through the comments, the current status of this is: you can release the 3.1.0 package that was uploaded to pypi.

---

Could someone please remove the existing cached 3.1.0 pre-release of django-simple-history?  We found a late issue and I updated the 3.1.0 tag and I am trying to publish 3.1.0 to you again.  3.1.0 was never published to PyPI so this is safe.

https://github.com/jazzband/django-simple-history/runs/6136987089?check_suite_focus=true

```
Checking dist/django_simple_history-3.1.0-py2.py3-none-any.whl: PASSED
Checking dist/django-simple-history-3.1.0.tar.gz: PASSED
Uploading distributions to 
https://jazzband.co/projects/django-simple-history/upload
Uploading django_simple_history-3.1.0-py2.py3-none-any.whl
...
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.5/121.5 kB • 00:00 • 932.6 kB/s
[25](https://github.com/jazzband/django-simple-history/runs/6136987089?check_suite_focus=true#step:7:25)hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from                                        
         https://jazzband.co/projects/django-simple-history/upload              
         File already exists.
```

Once this file is cleared then I can restart this release build and put the updated 3.1.0 there, and let you know.

**Comment by hugovk** [comment]
We have a bit of a roadie bottleneck so it'll be quicker for you to release as something like 3.1.1 instead.

**Comment by 1ace** [comment]
Rewriting published history is generally a bad idea and causes issues everywhere; you shouldn't have changed the contents of `3.1.0` but made a new release instead 🙂

**Comment by jeking3** [comment]
It was a pre-release, tagged but never officially released.  It was my understanding as a pre-release that would not be a problem to update the tag.  In the future we can just move forward when this happens if that's the general consensus.

It sounds like there is no differentiation between pre-releases and releases when something is uploaded.  Can you provide any guidance there; for example should I change the name of a pre-release to django_simple_history-3.1.0+pre.1-py3-none-any.whl?  I also have to look at why the wheel includes py2 in the name.  I assumed the package wasn't uploaded to pypi because it was marked as a pre-release, not because of a backlog.

Thanks for the advice and assist.  I'll start the process of a 3.1.1 release shortly.

**Comment by jeking3** [comment]
Hello, you can release the 3.1.0 package to pypi.  All of the changes are for development and packaging purposes and none of them is a release blocker.  I will follow up with a separate 3.1.1 release hopefully this weekend.

**Comment by jeking3** [comment]
I also fixed the tag in the repo to match the release originally uploaded to you.,
