### ISSUE TITLE
How do I work on a project, once in Jazzband?

### ISSUE THREAD

**Issue by kytta** [jazzband/help#286]
So, I have joined Jazzband and picked a project I would like to dedicate my time to. I, as an org member, have full access to the repository, including the `master` branch. How should I work? Should I just push my changes to a branch and then merge them into `master`, or should I open PRs and ask the leads for a review? What about small or non-code changes, like README typos or docs? Are there any guidelines for this, because all I could find are project transfer guidelines.

**Comment by hugovk** [comment]
Welcome!

I don't think there are specific Jazzband guidelines, but you could check for a contributing guide (often `CONTRIBUTING.md`). Also you could check some of the existing "contributing to open source" guides out there (from a quick google: [1](https://opensource.guide/how-to-contribute/), [2](https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/), [3](https://stackoverflow.blog/2020/08/03/getting-started-with-contributing-to-open-source/)).

In general, it's a good idea to push changes to a branch and make a pull request. One huge benefit is it runs the tests on CI, often on multiple operating systems, to help avoid "works on my machine".

Also, by going through the motions and opening a PR and writing the reasoning, I sometimes find I've missed something and can update it.

If there are people available, it's always good having a second (or more) pairs of eyes check them. Especially so when first starting out on a project, as there may be some little gotchas that aren't immediately obvious.

I'd also make PRs for small/non-code/typo/docs changes, even if there's not much to say. Sometimes there can be docs linting that can pick things like RST problems.

Feel free to open issues to discuss changes first, especially larger ones, although a (draft) PR can also be a good starting point.

**Comment by kytta** [comment]
Thank you for the warm welcome and swift reply!

> you could check for a contributing guide (often `CONTRIBUTING.md`).

The repo's (it's [`django-simple-menu`](https://github.com/jazzband/django-simple-menu), btw) CONTRIBUTING.md only has links to the Jazzband's [CoC](https://jazzband.co/about/conduct) and [new/moved project guidelines](https://jazzband.co/about/guidelines)


> In general, it's a good idea to push changes to a branch and make a pull request. One huge benefit is it runs the tests on CI, often on multiple operating systems, to help avoid "works on my machine".

Yeah, that's what I've always been doing :) It feels wrong to do anything else at this point 😂 


> If there are people available, it's always good having a second (or more) pairs of eyes check them. Especially so when first starting out on a project, as there may be some little gotchas that aren't immediately obvious.

I've asked both project leads for reviews on my first PRs, but, judging from the state of the repository (no code updates since 2016, no overall updates since moving to Jazzband in 2021) and their activity graphs, I don't know if they'll respond any time soon 😅 

---

I'll be patient for a while, but realistically: what is the plan of action when project leads do not respond for a while and a project seems abandoned even inside Jazzband?

**Comment by hugovk** [comment]
> I'll be patient for a while, but realistically: what is the plan of action when project leads do not respond for a while and a project seems abandoned even inside Jazzband?

I guess the best thing would be to open a new issue on the repo and/or here to propose new project leads. 

Whilst you are able to merge PRs as a project member, a project lead is needed to release to PyPI, so it's something to resolve sooner rather than later.

**Comment by kytta** [comment]
Thank you for the explanations!
