### ISSUE TITLE
Can't join the Jazzband organization

### ISSUE THREAD

**Issue by ghost** [jazzband/help#288]
I tried adding myself to the jazzband organization, but I got the following error on the website:

```
Error
Looks like something went wrong.

Please open an issue for the roadies if the problem persists.
```

Can you help me with this? 😄

**Comment by jezdez** [comment]
Can you try again now?

**Comment by ghost** [comment]
Same error, still can't add myself to the organization 🥲.

**Comment by hugovk** [comment]
Closing because OP has since deleted their GitHub account.
