### ISSUE TITLE
PyPI Release: dj-database-url 1.0.0

### ISSUE THREAD

**Issue by mattseymour** [jazzband/help#292]
# PyPI Release

There is currently no lead specified on the dj-database-url project though i have raised a ticket to take over this role (see #278 for my request for leadeship). 

While we are waiting can we please cut a 1.0.0 release of dj-database-urls. I say 1.0.0 because:

* The current project is 0.5.0 which it has been for a few years. It would be good to raise a new major verion seeing this is production code and that now the project is under new ownership.
* We have dropped support for python 2.7 as well as django < 2.0

Additional notes:
* @jacobian is still listed as the pypi owner, jazzband will need to be added to the pypi maintainer list.
* Pypi needs links update and maintained, its still pointing to its original repo.

**Comment by hugovk** [comment]
> * Pypi needs links update and maintained, its still pointing to its original repo.

The links on PyPI come from the README, which has been updated, so this will be fixed in the next release.

**Comment by mattseymour** [comment]
Awesome thank you @jacobian for your help.

**Comment by jezdez** [comment]
This has been done.
