### ISSUE TITLE
Can Jazzband leads participate in the PyPI 2FA Security Key Giveaway?

### ISSUE THREAD

**Issue by rayrrr** [jazzband/help#303]
In the wake of the Log4J vulnerability, PyPi is running a [PyPI 2FA Security Key Giveaway](https://pypi.org/security-key-giveaway/) for maintainers of "critical" projects, as defined by being among the top 1% of packages downloaded on PyPi. Full disclosure: I am the current lead for one of these projects. 

Several other Jazzband-maintained projects fall under this banner as well, [as can be seen here](https://hugovk.github.io/top-pypi-packages/) (thanks @hugovk!). However, PyPi tracks eligibility based on who is the listed maintainer on PyPi, and I believe that "jazzband" is the listed maintainer for all these projects. Since Project Leads are not individually listed as the maintainers on PyPi, we are not being individually recognized as eligible for the giveaway on the PyPi site.

@jezdez, is there a way you, or someone you assign to the task, could reach out to PyPi folks, explain the Jazzband model, and show them the jazzband.co website to reflect who should be eligible for the giveaway, and see if the appropriate folks could be granted that eligibility?

I think it would both enhance security and be a nice piece of swag for our volunteer maintainers.

Thanks!

**Comment by hugovk** [comment]
I'm not sure if we should: the idea of the giveaway is to increase security of the Python community as a whole by getting as many maintainers of critical packages who don't currently have 2FA enabled, to enable it, to make it less likely third parties can access their accounts and upload something malicious.

But with Jazzband, uploads to PyPI are semi-automated via the Jazzband staging area, which means project leads usually don't need (and usually don't have) direct maintainer access to the package on PyPI, and therefore don't actually need a 2FA key for uploading.

As the number of keys are limited ([4,000](https://pypi.org/security-key-giveaway/)), I think they should rather first go to those "PyPI Users Identified as Critical" ([8,243](https://p.datadoghq.com/sb/7dc8b3250-389f47d638b967dbb8f7edfd4c46acb1?theme=dark&from_ts=1657961594324&to_ts=1658047994324&live=true)) who actually do upload directly to PyPI.

In any case, I recommend everyone enables 2FA on PyPI and here on GitHub (and GitHub will require it for all ["by the end of 2023"](https://github.blog/2022-05-04-software-security-starts-with-the-developer-securing-developer-accounts-with-2fa/)).

**Comment by jezdez** [comment]
I'm closing this since the the 2FA key giveway is over.
