### ISSUE TITLE
Project Lead: django-analytical

### ISSUE THREAD

**Issue by bittner** [jazzband/help#304]
# Project lead request

I suggest to add @smithdc1 as an [additional project lead](https://jazzband.co/projects/django-analytical).

David has made [some significant contributions](https://github.com/jazzband/django-analytical/graphs/contributors), starting with the migration of our test suite to pytest, and is usually quick to answer and react on issues and PRs.

**Comment by jezdez** [comment]
Done, @smithdc1 let me know if you're NOT interested in this!
