### ISSUE TITLE
Proposal: django-avatar

### ISSUE THREAD

**Issue by johanneswilm** [jazzband/help#305]
# Project Proposal

Please fill in the details below to confirm you adhere to the [Jazzband Guidelines](https://jazzband.co/about/guidelines), and also add the package name to the issue title.

## Project Details
django-avatar

Official last Pip release made from: https://github.com/grantmcconnaughey/django-avatar

Current code: https://github.com/johanneswilm/django-avatar/

## Project Description
Django-avatar is a reusable application for handling user avatars. It has the ability to default to Gravatar if no avatar is found for a certain user. Django-avatar automatically generates thumbnails and stores them to your default file storage backend for retrieval later.

For more information see the documentation at http://django-avatar.readthedocs.org/

## Project Leads
Current maintainer was @grantmcconnaughey but he has given up on maintenance. See explanation here https://github.com/pypa/pypi-support/issues/2114

## Confirmation of Guidelines

Please confirm the following:

- [X] I am the project owner, or have permission from the project owner, to request a transfer.

Current maintainer [has previously agreed to move package to JazzBand](https://github.com/grantmcconnaughey/django-avatar/pull/209#issuecomment-1124036891), but has since gone silent. 

- [X] This project is a [viable candidate](https://jazzband.co/about/guidelines#viability) for Jazzband.

- [X] This project fulfills the [documentation requirements](https://jazzband.co/about/guidelines#documentation).

- [X] This project is [tested](https://jazzband.co/about/guidelines#tests).

- [X] I am happy to adopt Jazzband's [code of conduct](https://jazzband.co/about/guidelines#conduct) in this project.

- [X] I am happy to include Jazzband's [contributing guidelines](https://jazzband.co/about/guidelines#contributing-guidelines) in this project.

**Comment by johanneswilm** [comment]
Ok, I've tweeted here to try to get his attention: https://twitter.com/fiduswriter/status/1557024914124701701 . It sounds like he done working on open source software, but hopefully he will make an exception for this.

**Comment by grantmcconnaughey** [comment]
@jezdez I transferred the repo to jazzband: https://github.com/jazzband/django-avatar

Is there anything I need to do on the PyPI side of things?

**Comment by jezdez** [comment]
> @jezdez I transferred the repo to jazzband: https://github.com/jazzband/django-avatar
> 
> Is there anything I need to do on the PyPI side of things?

Nope, I still have owner permissions and can handle it. Thank you for your work over the years, this is really appreciated!

**Comment by grantmcconnaughey** [comment]
Awesome, that simplifies things. 😄  Best of luck, folks!

**Comment by johanneswilm** [comment]
@grantmcconnaughey OK, I understand. Thank you so much and good luck with everything going forward!

**Comment by jezdez** [comment]
Closing now that https://github.com/jazzband/django-avatar/issues/211 has been opened.
