### ISSUE TITLE
Project Lead: django-constance

### ISSUE THREAD

**Issue by Natim** [jazzband/help#306]
# Project lead request

Hello, I'd lilke to join django-constance in order to release the 2.9.1 version.

Refs https://github.com/jazzband/django-constance/compare/2.9.0...master
Refs https://github.com/jazzband/django-constance/issues/495

**Comment by jezdez** [comment]
@Natim Your help would be really appreciated with django-constance! You still interested?

**Comment by Natim** [comment]
Yes ok why not!

**Comment by jezdez** [comment]
Done! Thank you <3
