### ISSUE TITLE
Capability to merge blocked despite approved reviews

### ISSUE THREAD

**Issue by ticosax** [jazzband/help#311]
Hi,
We have a blocked Pull Request, that prevents the project to welcome new contribution, as this PR lacks an approval from another maintainer with write permissions.
https://github.com/jazzband/django-fsm-log/pull/144

I would like to know if you have any recommendation for actions I could take, to unblock the project ?

Thanks.

**Comment by hugovk** [comment]
I've approved and merged it. 👍

**Comment by hugovk** [comment]
Re-opening as I guess we need to improve the process for next time.

If you can find another person to join Jazzband and help review (I'm not available to do it regularly), that would be best as it makes sure everything is reviewed before merge. Would @lorenzomorandini be interested?

Otherwise we could ask the Jazzband roadie to remove that review requirement.

**Comment by lorenzomorandini** [comment]
@hugovk I could be interested but was the question related to only django-fsm-log package or any Jazzband project in general?

**Comment by hugovk** [comment]
Great! The question was about django-fsm-log (but you can join others if you're interested too).

See:

https://jazzband.co/projects/django-fsm-log

And have a read through the other info at https://jazzband.co/, there's not too much :)

**Comment by ticosax** [comment]
Sounds like a good initiative @hugovk, thanks.
@lorenzomorandini I welcome you to become another maintainer of django-fsm-log, if you like. Being the currently only active one, is not ideal for the project.

**Comment by lorenzomorandini** [comment]
@ticosax I am definetly interested, thanks.

**Comment by ticosax** [comment]
@lorenzomorandini, you can make a formal request to join the projects leads of django-fsm-log https://github.com/jazzband/help/issues/new?assignees=&labels=lead&template=project_lead.md&title=Project+Lead%3A+%3CPACKAGE+NAME%3E

**Comment by lorenzomorandini** [comment]
@ticosax done, thanks.
