### ISSUE TITLE
Project Lead: django-fsm-log

### ISSUE THREAD

**Issue by lorenzomorandini** [jazzband/help#317]
# Project lead request

As per [issue](https://github.com/jazzband/help/issues/311#issuecomment-1307376103) it was suggested that I could help in maintaining the django-fsm-log package. The company I work for currently uses it for internal projects and I'd be interested in making sure it stays up-to-date by helping @ticosax.

**Comment by jezdez** [comment]
@lorenzomorandini Please join the Jazzband GitHub org via https://jazzband.co/join. I can't add you as project lead without you being member first. Thank you!

**Comment by lorenzomorandini** [comment]
@jezdez just did, thanks!

**Comment by jezdez** [comment]
Okay, I've added you to the project leads (next to @ticosax and @MRigal): https://jazzband.co/projects/django-fsm-log

Please read the [guidelines](https://jazzband.co/about/guidelines), [release docs](https://jazzband.co/about/releases) and [FAQ](https://jazzband.co/about/faq), in case you haven't yet.

When a new release is tagged, the package is automatically uploaded to the Jazzband staging package index using the [release workflow](https://github.com/jazzband/django-fsm-log/blob/master/.github/workflows/release.yml). As a project lead you'll get an email with more details how to actually deploy the uploaded file(s) to PyPI from that point on. Please don't hesitate to use the [GitHub project team](https://github.com/orgs/jazzband/teams/django-fsm-log) to chat with other members.

**Comment by ticosax** [comment]
Thank you @jezdez
