### ISSUE TITLE
Project Lead: django-simple-menu

### ISSUE THREAD

**Issue by kytta** [jazzband/help#320]
# Project lead request

`django-simple-menu` is the package I use at my job, so it is pretty important for me that this package stays maintained. I have been merging bugfixes, features, and new documentation to it over the last few months, including the release of the v2.0.0 which (finally) fixed the PyPI metadata.

I want to become the lead so that new releases can come out a bit quicker.

One of the current leads, @mbeijen, [approved me becoming a lead](https://github.com/jazzband/django-simple-menu/pull/112#issuecomment-1328805183), so I could release new versions of the package. I hope @borgstrom will also have not much against it. :)

**Comment by jezdez** [comment]
Done!
