### ISSUE TITLE
Proposing django-taggit-serializer

### ISSUE THREAD

**Issue by Fohlen** [jazzband/help#91]
Hello there folks! On behalf of @mecodia and @glemmaPaul I am proposing to move the [django-taggit-serializer](https://github.com/glemmaPaul/django-taggit-serializer/issues/44) project to jazzband, so that it can have more attention being paid to it in the future. Please let us know what you guys think over here:

- will it be feasible for the jazzband organisation to handle this package?
- what steps need to be taken in order to make this happen?
- @glemmaPaul would of course still like to be involved in maintaining the package. Is this feasible with your community guidelines?

**Comment by nat-yaml** [comment]
+1

**Comment by ksitko** [comment]
Hey guys, any chance this could be further considered? django-taggit already is under jazzband's umbrella, given the rather significant popularity of django-rest-framework it seems almost like taggit is incomplete without a serializer.

**Comment by jezdez** [comment]
@Fohlen @glemmaPaul @ksitko Hey friends, this is long overdue to say the least, but yeah, this project looks like a good match.

Just join the Jazzband org on https://jazzband.co/ and transfer the repo using the regular GitHub repo transfer tool. A separate issue with TODOs to finalize the transfer will be created automatically and can be worked on once the project is under the Jazzband.

**Comment by stephsamson** [comment]
Would it be possible to just have a fork of django-taggit-serializer under jazzband?

**Comment by jezdez** [comment]
> Would it be possible to just have a fork of django-taggit-serializer under jazzband?

Unfortunately that won't give access to the PyPI project and complicates maintenance. I would suggest to reach out toe @glemmaPaul by email to figure out if https://github.com/glemmaPaul/django-taggit-serializer/issues/44 is still something that they'd be interested. Alternatively I would suggest to propose the functionality to django-taggit itself.

**Comment by rtpg** [comment]
I have reached out to Paul regarding this topic. I believe that having django-taggit absorb the serializer code makes the most sense overall, as it's a pretty relevant piece of functionality.

**Comment by rtpg** [comment]
Alright, I had tried reaching out to Paul and didn't get a response (on top of non-responses to other people on this topic).

Given the license compatibility (see [this issue](https://github.com/jazzband/django-taggit/issues/707#issuecomment-864403197)) for the projects, I opted for vendoring in the project and including attribution to Paul in several places in the codebase. 

I believe this is following the licensing of the respective codebases correctly, and I also believe this is what makes sense on an organizational level as well (the serializer stuff was just one file, having it all in one package is just easier to maintain)
